# Bluestock Mutual Fund Analytics

## 01 - Data Ingestion

This notebook loads the 10 original mutual fund datasets and performs
basic data validation including dataset dimensions, data types,
missing values, duplicate records, and initial observations.

In [38]:
from pathlib import Path
import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

In [39]:
PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"

print("Project root:", PROJECT_ROOT)
print("Raw data folder:", RAW_DIR)
print("Raw folder exists:", RAW_DIR.exists())

Project root: c:\Users\Farhan\bluestock_mf_capstone
Raw data folder: c:\Users\Farhan\bluestock_mf_capstone\data\raw
Raw folder exists: True

In [40]:
csv_files = sorted(
    [
        f for f in RAW_DIR.glob("*.csv")
        if not f.name.endswith("_live_nav.csv")
    ]
)

print("Original datasets found:", len(csv_files))

for file in csv_files:
    print(file.name)

Original datasets found: 10
1788499980509-304c1255-08_investor_transactions.csv
1788499982117-e3d6ab98-09_portfolio_holdings.csv
1788499982615-f9647ab2-10_benchmark_indices.csv
1788499983331-4389156d-02_nav_history.csv
1788499984134-b0cbf625-03_aum_by_fund_house.csv
1788499984405-d702a6c6-04_monthly_sip_inflows.csv
1788499984721-4b860901-05_category_inflows.csv
1788499985036-da4a0c4a-06_industry_folio_count.csv
1788499985420-bb134abf-07_scheme_performance.csv
fund_master.csv

In [41]:
datasets = {}

for file in csv_files:
    try:
        df = pd.read_csv(file)
        datasets[file.stem] = df
        print(f"Loaded: {file.name}")
        print(f"Shape: {df.shape}")
        print("-" * 60)
    except Exception as e:
        print(f"ERROR: {file.name}")
        print(e)

Loaded: 1788499980509-304c1255-08_investor_transactions.csv
Shape: (32778, 13)
------------------------------------------------------------
Loaded: 1788499982117-e3d6ab98-09_portfolio_holdings.csv
Shape: (322, 8)
------------------------------------------------------------
Loaded: 1788499982615-f9647ab2-10_benchmark_indices.csv
Shape: (8050, 3)
------------------------------------------------------------
Loaded: 1788499983331-4389156d-02_nav_history.csv
Shape: (46000, 3)
------------------------------------------------------------
Loaded: 1788499984134-b0cbf625-03_aum_by_fund_house.csv
Shape: (90, 5)
------------------------------------------------------------
Loaded: 1788499984405-d702a6c6-04_monthly_sip_inflows.csv
Shape: (48, 6)
------------------------------------------------------------
Loaded: 1788499984721-4b860901-05_category_inflows.csv
Shape: (144, 3)
------------------------------------------------------------
Loaded: 1788499985036-da4a0c4a-06_industry_folio_count.csv
Shape: (21, 6)
------------------------------------------------------------
Loaded: 1788499985420-bb134abf-07_scheme_performance.csv
Shape: (40, 19)
------------------------------------------------------------
Loaded: fund_master.csv
Shape: (40, 15)
------------------------------------------------------------

In [42]:
summary = []

for name, df in datasets.items():
    summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": int(df.duplicated().sum()),
        "missing_cells": int(df.isna().sum().sum())
    })

summary_df = pd.DataFrame(summary)

summary_df

,dataset,rows,columns,duplicate_rows,missing_cells
0,1788499980509-304c1255-08_investor_transactions,32778,13,0,0
1,1788499982117-e3d6ab98-09_portfolio_holdings,322,8,0,0
2,1788499982615-f9647ab2-10_benchmark_indices,8050,3,0,0
3,1788499983331-4389156d-02_nav_history,46000,3,0,0
4,1788499984134-b0cbf625-03_aum_by_fund_house,90,5,0,0
5,1788499984405-d702a6c6-04_monthly_sip_inflows,48,6,0,12
6,1788499984721-4b860901-05_category_inflows,144,3,0,0
7,1788499985036-da4a0c4a-06_industry_folio_count,21,6,0,0
8,1788499985420-bb134abf-07_scheme_performance,40,19,0,0
9,fund_master,40,15,0,0

In [43]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)
    display(df.dtypes.to_frame("data_type"))

======================================================================
1788499980509-304c1255-08_investor_transactions
======================================================================

                   data_type
investor_id              str
transaction_date         str
amfi_code              int64
transaction_type         str
amount_inr             int64
state                    str
city                     str
city_tier                str
age_group                str
gender                   str
annual_income_lakh   float64
payment_mode             str
kyc_status               str

======================================================================
1788499982117-e3d6ab98-09_portfolio_holdings
======================================================================

                  data_type
amfi_code             int64
stock_symbol            str
stock_name              str
sector                  str
weight_pct          float64
market_value_cr     float64
current_price_inr   float64
portfolio_date          str

======================================================================
1788499982615-f9647ab2-10_benchmark_indices
======================================================================

            data_type
date              str
index_name        str
close_value   float64

======================================================================
1788499983331-4389156d-02_nav_history
======================================================================

          data_type
amfi_code     int64
date            str
nav         float64

======================================================================
1788499984134-b0cbf625-03_aum_by_fund_house
======================================================================

               data_type
date                 str
fund_house           str
aum_lakh_crore   float64
aum_crore          int64
num_schemes        int64

======================================================================
1788499984405-d702a6c6-04_monthly_sip_inflows
======================================================================

                          data_type
month                           str
sip_inflow_crore              int64
active_sip_accounts_crore   float64
new_sip_accounts_lakh       float64
sip_aum_lakh_crore          float64
yoy_growth_pct              float64

======================================================================
1788499984721-4b860901-05_category_inflows
======================================================================

                 data_type
month                  str
category               str
net_inflow_crore   float64

======================================================================
1788499985036-da4a0c4a-06_industry_folio_count
======================================================================

                    data_type
month                     str
total_folios_crore    float64
equity_folios_crore   float64
debt_folios_crore     float64
hybrid_folios_crore   float64
others_folios_crore   float64

======================================================================
1788499985420-bb134abf-07_scheme_performance
======================================================================

                   data_type
amfi_code              int64
scheme_name              str
fund_house               str
category                 str
plan                     str
return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
alpha                float64
beta                 float64
sharpe_ratio         float64
sortino_ratio        float64
std_dev_ann_pct      float64
max_drawdown_pct     float64
aum_crore              int64
expense_ratio_pct    float64
morningstar_rating     int64
risk_grade               str

======================================================================
fund_master
======================================================================

                   data_type
amfi_code              int64
fund_house               str
scheme_name              str
category                 str
sub_category             str
plan                     str
launch_date              str
benchmark                str
expense_ratio_pct    float64
exit_load_pct        float64
min_sip_amount         int64
min_lumpsum_amount     int64
fund_manager             str
risk_category            str
sebi_category_code       str

In [44]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)
    display(df.head())

======================================================================
1788499980509-304c1255-08_investor_transactions
======================================================================

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

======================================================================
1788499982117-e3d6ab98-09_portfolio_holdings
======================================================================

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

======================================================================
1788499982615-f9647ab2-10_benchmark_indices
======================================================================

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

======================================================================
1788499983331-4389156d-02_nav_history
======================================================================

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

======================================================================
1788499984134-b0cbf625-03_aum_by_fund_house
======================================================================

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

======================================================================
1788499984405-d702a6c6-04_monthly_sip_inflows
======================================================================

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

======================================================================
1788499984721-4b860901-05_category_inflows
======================================================================

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

======================================================================
1788499985036-da4a0c4a-06_industry_folio_count
======================================================================

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

======================================================================
1788499985420-bb134abf-07_scheme_performance
======================================================================

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

======================================================================
fund_master
======================================================================

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [45]:
for name, df in datasets.items():
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    if missing.empty:
        print("No missing values.")
    else:
        display(missing.to_frame("missing_count"))

======================================================================
1788499980509-304c1255-08_investor_transactions
======================================================================
No missing values.

======================================================================
1788499982117-e3d6ab98-09_portfolio_holdings
======================================================================
No missing values.

======================================================================
1788499982615-f9647ab2-10_benchmark_indices
======================================================================
No missing values.

======================================================================
1788499983331-4389156d-02_nav_history
======================================================================
No missing values.

======================================================================
1788499984134-b0cbf625-03_aum_by_fund_house
======================================================================
No missing values.

======================================================================
1788499984405-d702a6c6-04_monthly_sip_inflows
======================================================================

                missing_count
yoy_growth_pct             12

======================================================================
1788499984721-4b860901-05_category_inflows
======================================================================
No missing values.

======================================================================
1788499985036-da4a0c4a-06_industry_folio_count
======================================================================
No missing values.

======================================================================
1788499985420-bb134abf-07_scheme_performance
======================================================================
No missing values.

======================================================================
fund_master
======================================================================
No missing values.

In [46]:
duplicate_results = []

for name, df in datasets.items():
    duplicate_results.append({
        "dataset": name,
        "duplicate_rows": int(df.duplicated().sum())
    })

duplicate_df = pd.DataFrame(duplicate_results)

duplicate_df

                                           dataset  duplicate_rows
0  1788499980509-304c1255-08_investor_transactions               0
1     1788499982117-e3d6ab98-09_portfolio_holdings               0
2      1788499982615-f9647ab2-10_benchmark_indices               0
3            1788499983331-4389156d-02_nav_history               0
4      1788499984134-b0cbf625-03_aum_by_fund_house               0
5    1788499984405-d702a6c6-04_monthly_sip_inflows               0
6       1788499984721-4b860901-05_category_inflows               0
7   1788499985036-da4a0c4a-06_industry_folio_count               0
8     1788499985420-bb134abf-07_scheme_performance               0
9                                      fund_master               0

In [47]:
for name, df in datasets.items():
    numeric_cols = df.select_dtypes(include=np.number).columns

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    if len(numeric_cols) > 0:
        display(df[numeric_cols].describe().T)
    else:
        print("No numeric columns.")

======================================================================
1788499980509-304c1255-08_investor_transactions
======================================================================

,count,mean,std,min,25%,50%,75%,max
amfi_code,32778.0,120264.617518,14370.205345,100016.0,118632.0,119551.0,120843.00,149324.0
amount_inr,32778.0,107437.318628,150415.905084,400.0,3153.0,17782.5,189324.25,597498.0
annual_income_lakh,32778.0,26.181219,20.805425,3.0,10.6,19.7,37.40,99.7

======================================================================
1788499982117-e3d6ab98-09_portfolio_holdings
======================================================================

,count,mean,std,min,25%,50%,75%,max
amfi_code,322.0,121210.434783,14669.377920,100016.00,118633.0000,119552.000,120842.7500,149324.00
weight_pct,322.0,10.558975,6.060137,0.99,6.0150,9.395,13.9175,38.18
market_value_cr,322.0,1008.846646,543.827535,55.74,513.7025,1045.670,1477.5025,1999.50
current_price_inr,322.0,4080.870528,2265.186353,246.78,2081.9850,4138.995,5914.3075,7942.96

======================================================================
1788499982615-f9647ab2-10_benchmark_indices
======================================================================

,count,mean,std,min,25%,50%,75%,max
close_value,8050.0,18351.950181,14169.995121,1444.13,2819.0625,18392.96,26539.0975,79075.39

======================================================================
1788499983331-4389156d-02_nav_history
======================================================================

,count,mean,std,min,25%,50%,75%,max
amfi_code,46000.0,120247.000000,14352.317221,100016.0000,118632.750000,119551.50000,120842.250000,149324.0000
nav,46000.0,269.570265,577.187060,26.1366,69.170425,122.73215,260.338675,4268.5497

======================================================================
1788499984134-b0cbf625-03_aum_by_fund_house
======================================================================

,count,mean,std,min,25%,50%,75%,max
aum_lakh_crore,90.0,4.352889,2.734328,1.05,2.525,3.45,5.675,12.5
aum_crore,90.0,435288.888889,273432.827420,105000.00,252500.000,345000.00,567500.000,1250000.0
num_schemes,90.0,152.200000,52.108832,56.00,95.000,172.50,195.000,216.0

======================================================================
1788499984405-d702a6c6-04_monthly_sip_inflows
======================================================================

,count,mean,std,min,25%,50%,75%,max
sip_inflow_crore,48.0,19577.520833,6354.329621,11438.00,13658.500,18224.000,25944.2500,31002.00
active_sip_accounts_crore,48.0,7.189583,1.271457,4.91,6.110,7.150,8.3000,9.35
new_sip_accounts_lakh,48.0,9.893750,5.370745,7.50,8.775,9.200,9.5625,46.00
sip_aum_lakh_crore,48.0,8.632083,3.613579,4.80,5.790,7.265,10.5250,15.90
yoy_growth_pct,36.0,31.456944,11.768190,15.80,20.245,28.295,40.8075,53.05

======================================================================
1788499984721-4b860901-05_category_inflows
======================================================================

,count,mean,std,min,25%,50%,75%,max
net_inflow_crore,144.0,6473.881944,9718.335947,437.0,1801.25,4148.0,5304.0,41952.0

======================================================================
1788499985036-da4a0c4a-06_industry_folio_count
======================================================================

,count,mean,std,min,25%,50%,75%,max
total_folios_crore,21.0,19.829524,4.583376,13.26,15.54,19.98,23.89,26.12
equity_folios_crore,21.0,13.880476,3.207799,9.28,10.88,13.99,16.72,18.28
debt_folios_crore,21.0,2.776190,0.640308,1.86,2.18,2.80,3.34,3.66
hybrid_folios_crore,21.0,1.190000,0.274864,0.80,0.93,1.20,1.43,1.57
others_folios_crore,21.0,1.983333,0.459079,1.33,1.55,2.00,2.39,2.61

======================================================================
1788499985420-bb134abf-07_scheme_performance
======================================================================

,count,mean,std,min,25%,50%,75%,max
amfi_code,40.0,120247.00000,14534.998667,100016.00,118632.7500,119551.500,120842.2500,149324.00
return_1yr_pct,40.0,14.37600,4.883023,4.26,11.7350,14.620,16.3925,24.93
return_3yr_pct,40.0,14.08900,4.617253,5.14,12.0350,14.205,15.8825,23.39
return_5yr_pct,40.0,14.51675,4.454021,5.43,12.3400,14.185,17.5850,23.80
benchmark_3yr_pct,40.0,12.83550,4.740972,3.96,10.6900,13.090,14.7750,22.16
alpha,40.0,1.25350,0.447412,0.51,0.8875,1.205,1.7000,1.98
beta,40.0,0.87325,0.224846,0.22,0.8900,0.960,1.0000,1.04
sharpe_ratio,40.0,1.36175,1.475805,0.80,0.8650,0.925,0.9850,7.68
sortino_ratio,40.0,2.08250,2.203144,1.03,1.2700,1.445,1.6375,10.37
std_dev_ann_pct,40.0,14.96250,6.669282,0.50,14.0000,14.000,19.0000,25.00
max_drawdown_pct,40.0,-19.20025,8.819164,-33.50,-25.0625,-20.600,-14.2550,-2.23
aum_crore,40.0,26091.60000,13809.111340,979.00,17400.5000,26713.000,38125.0000,49046.00
expense_ratio_pct,40.0,1.23700,0.386584,0.55,0.7875,1.425,1.5400,1.64
morningstar_rating,40.0,4.25000,0.742484,3.00,4.0000,4.000,5.0000,5.00

======================================================================
fund_master
======================================================================

,count,mean,std,min,25%,50%,75%,max
amfi_code,40.0,120247.0000,14534.998667,100016.00,118632.7500,119551.500,120842.25,149324.00
expense_ratio_pct,40.0,1.2370,0.386584,0.55,0.7875,1.425,1.54,1.64
exit_load_pct,40.0,0.8125,0.387091,0.00,1.0000,1.000,1.00,1.00
min_sip_amount,40.0,500.0000,0.000000,500.00,500.0000,500.000,500.00,500.00
min_lumpsum_amount,40.0,1277.5000,1082.847031,100.00,1000.0000,1000.000,1000.00,5000.00

## Initial Data Quality Observations

- All 10 original mutual fund datasets were successfully loaded using Pandas.
- Dataset dimensions and column structures were inspected.
- Data types were reviewed for all columns.
- Duplicate records were checked across all datasets.
- Missing values were identified and documented.
- Numeric columns were summarized using descriptive statistics.
- Original raw datasets were preserved without modification.
- Further cleaning and transformation will be performed in the next notebook.